<?php

namespace Avtomat\Box;

use Avtomat\Contracts\BoxContract;

/**
 * Class EqualConstBox
 * @package Avtomat\Box
 */
class EqualConstBox extends Box implements BoxContract
{
    public function run($inputData)
    {
        parent::run($inputData); // TODO: Change the autogenerated stub
    }
}